routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login', 'AuthController@auth')->name('auth_login');
Route::get('/logout', 'AuthController@logout')->name('logout');

Route::group(['middleware' => 'backend.auth:backend'], function() {
    Route::get('/', 'OrderController@index');

    Route::group(['prefix' => 'account'], function () {
        Route::post('/confirm', 'AccountController@confirm')->name('account.create.confirm');
        Route::post('/{id}/confirm', 'AccountController@confirm')->name('account.edit.confirm');
    });
    Route::resource('account', 'AccountController')->except(['show']);

    Route::group(['prefix' => 'banner'], function () {
        Route::post('/create/confirm', 'BannerController@createConfirm')->name('banner.create_confirm');
        Route::post('/edit/{id}/confirm', 'BannerController@editConfirm')->name('banner.edit_confirm');
    });
    Route::resource('banner', 'BannerController')->except(['show']);
    Route::resource('category', 'CategoryController')->only(['index']);

    Route::group(['prefix' => 'information'], function () {
        Route::post('/create/confirm', 'InformationController@confirm')->name('information.create.confirm');
        Route::post('/{id}/confirm', 'InformationController@confirm')->name('information.edit.confirm');
    });
    Route::resource('information', 'InformationController')->except(['show']);


    Route::resource('order', 'OrderController')->only(['index','show']);
    Route::get('order/{area_id}/{city_id}/shop', 'OrderController@getShop')->name('order.get.shop');

    Route::group(['prefix' => 'shop'], function () {
        Route::post('/confirm', 'ShopController@confirm')->name('shop.create.confirm');
        Route::post('/{id}/confirm', 'ShopController@confirm')->name('shop.edit.confirm');
        Route::get('/{area_id}/city', 'ShopController@getCity')->name('shop.get.city');
        Route::get('/getCity',"ShopController@getCityTest")->name('shop.getCity');

    });

    Route::resource('shop', 'ShopController')->except(['show']);
    Route::resource('user', 'UserController')->only(['index','show']);

    Route::group(['prefix' => 'event'], function () {
        Route::get('/index', 'EventController@index')->name('event.index');
        Route::get('/category', 'EventController@category')->name('event.category');
        Route::get('/item', 'EventController@item')->name('event.item');
        Route::get('/view', 'EventController@view')->name('event.view');
    });
    Route::group(['prefix' => 'item'], function () {
        Route::get('/index', 'ItemController@index')->name('item.index');
        Route::get('/detail', 'ItemController@detail')->name('item.detail');
        Route::get('/limited', 'ItemController@limited')->name('item.limited');
        Route::get('/list', 'ItemController@search')->name('item.list');
        Route::get('/name', 'ItemController@name')->name('item.name');
        Route::get('/point', 'ItemController@point')->name('item.point');
        Route::get('/price', 'ItemController@price')->name('item.price');
        Route::get('/shopCount', 'ItemController@shopCount')->name('item.shop_count');
        Route::get('/{category_code}/event', 'ItemController@getEventByCategory')->name('item.get.event');
        Route::get('/{item_code}/{shop_code}/{flag}', 'ItemController@updateStopFlag')->name('item.update.flag');

    });
});

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;


Route::middleware('web')->group(function () {
    Route::get('/', 'SiteController@index')->name('site.index');
    Route::get('/login', 'LoginController@index')->name('frontend.login');
    Route::get('/login-confirm', 'LoginController@loginConfirm')->name('frontend.login.confirm');
    Route::post('login', 'LoginController@authenticate')->name('authenticate_login');
    Route::get('/logout', 'LoginController@logout')->name('frontend.logout');
    Route::get('/password-reissue/{token}', 'SiteController@passwordReissue')->name('site.password_reissue');
    Route::post('/password-reissue', 'SiteController@passwordReissueAction')->name('site.password_reissue_action');
    Route::get('/password-reissue-comp', 'SiteController@passwordReissueComp')->name('site.password_reissue_comp');
    Route::get('/password-reminder', 'SiteController@passwordReminder')->name('site.password_reminder');
    Route::post('password-reminder', 'SiteController@sendMailPasswordReissue')->name('site.send_mail_password_reissue');
    //AJAX
    Route::group(['prefix' => 'ajax'], function () {
        Route::post('/render-by-map', 'AjaxController@renderShopByMap')->name('site.ajax.render_by_map');
        Route::post('/render-shop-by-city', 'AjaxController@renderShopByCity')->name('site.ajax.render_shop_by_city');
        Route::post('/get-event', 'AjaxController@getEvent')->name('site.ajax.get_event');
        Route::post('/get-product', 'AjaxController@getProduct')->name('site.ajax.get_product');
        Route::post('/render-city-popup', 'AjaxController@renderCityPopup')->name('site.render_city_popup');
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('/detail/{id}/{shopcode}/{keyitem}/{keyprouct}', 'ProductController@detail')->name('product.detail');
    });

    Route::get('/information-detail/{id}', 'InformationController@detail')->name('information.detail');

    Route::group(['prefix' => 'cart'], function () {
        Route::get('/', 'CartController@index')->name('cart.index');
        Route::get('/confirm', 'CartController@confirm')->name('cart.confirm');
        Route::get('/complete', 'CartController@complete')->name('cart.complete');
        Route::post('/add-to-cart', 'CartController@addToCart')->name('cart.add_to_cart');
        Route::post('/remove-item-cart', 'CartController@removeItemCart')->name('cart.remove_item_cart');
        Route::post('/on-load-box-cart', 'CartController@onLoadBoxCart')->name('cart.on_load_box_cart');
        Route::post('/check-item-cart', 'CartController@checkItemCart')->name('cart.check_item_cart');
        Route::post('/change-number-cart', 'CartController@changeNumberCart')->name('cart.change_number_cart');
        Route::post('/insert-cart', 'CartController@insertCart')->name('cart.insert_cart');
        Route::get('/not-registration', 'CartController@notRegistration')->name('cart.notregistration');
        Route::post('/not-registration-action', 'CartController@notRegistrationAction')->name('cart.notregistration.action');
        Route::post('/show-popup-remove', 'CartController@showPopupRemove')->name('cart.show_popup_remove');
    });

    Route::group(['prefix' => 'entry'], function () {
        Route::get('/', 'EntryController@index')->name('entry.index');
        Route::post('/','EntryController@postIndex')->name('entry.submit');
        Route::get('/register', 'EntryController@register')->name('entry.register');
    });

    Route::group(['prefix' => 'mypage','middleware'=>'frontend.auth'], function () {
        Route::get('', 'MypageController@index')->name('mypage.index');
        Route::get('/cancel-order-confirm/{slipNumber}', 'MypageController@cancelOrderConfirm')->name('mypage.cancel_order_confirm');
        Route::get('/cancel-order-complete/{slipNumber}', 'MypageController@cancelOrderComplete')->name('mypage.cancel_order_complete');
        Route::post('/cancel-order-complete-action', 'MypageController@updateCancelOrder')->name('mypage.cancel_order_complete_action');
        Route::get('/change_customer_info/{slip_number}', 'MypageController@changeCustomerInfo')->name('mypage.change_customer_info');
        Route::post('/change_customer_info/{slip_number}', 'MypageController@postChangeInfo')->name('mypage.post.change_customer_info');
        Route::post('/show-popup-cancel', 'MypageController@showPopupCancel')->name('mypage.show_popup_cancel');
    });
    Route::get('/change-password-entry', 'ChangeEmailPasswordController@changePasswordEntry')->name('mypage.change_password_entry');
    Route::post('/change-password-entry', 'ChangeEmailPasswordController@changePasswordEntryAction')->name('mypage.change_password_entry_action');
    Route::group(array('prefix' => 'static'), function () {
        Route::view('/guild', 'frontend/static/guild')->name('guild');
        Route::view('/privacy', 'frontend/static/privacy')->name('privacy');
        Route::view('/tokutei', 'frontend/static/tokutei')->name('tokutei');
        Route::view('/browser', 'frontend/static/browser')->name('browser');
        Route::view('/sitemap', 'frontend/static/sitemap')->name('sitemap');
        Route::view('/rule', 'frontend/static/rule')->name('rule');
        Route::get('/information', 'InformationController@index')->name('information');
        Route::get('/information/detail/{id}', 'InformationController@detail')->name('information.detail');
    });
});

routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/tsv', 'TsvController@index')->name('test.tsv');
Route::get('/tsv_all', 'TsvController@index_all')->name('test.tsv_all');
Route::get('/tsv_export', 'TsvExportController@export_tsv')->name('test.tsv_export');

app/Http/Controllers/Backend/AccountController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Http\Requests\AccountCreateRequest;
use App\Repositories\AccountRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends BackendController
{
    protected $accountRepository;

    public function __construct(AccountRepository $accountRepository)
    {
        $this->accountRepository = $accountRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $accounts = $this->accountRepository->searchCondition($request)->paginate(config('const.paging.backend'));
        return view('backend.account.index', compact('accounts'))
            ->with([
                'name' => $request->get('name'),
                'status' => $request->get('status'),
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        request()->session()->put('session_data', []);
        return view('backend.account.create');
    }

    /**
     * Show the form for confirm the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function confirm(AccountCreateRequest $request, $id = null)
    {
        $request->flash();
        $request->session()->put('session_data', $request->all());
        return view('backend.account.confirm')->with('account', $request->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(!$request->session()->has('session_data')){
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
        $data = $request->session()->get('session_data');
        $request->session()->forget('session_data');
        try {
            $this->accountRepository->create($data);
            return redirect()->route('account.index')->with('success', config('messages.DB_INSERT'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = $this->accountRepository->find($id);
        if ($account == null) {
            return redirect()->route('account.index')->with('error', config('messages.NO_DATA'));
        } else {
            $account = $account->toArray();
        }
        request()->session()->put('session_data', $account);
        return view('backend.account.create')->with('account', $account);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!$request->session()->has('session_data'))
        {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
        $data = $request->session()->get('session_data');
        $request->session()->forget('session_data');
        try {
            $this->accountRepository->update($id, $data);
            return redirect()->route('account.index')->with('success', config('messages.DB_UPDATE'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->accountRepository->softDelete($id);
            return redirect()->route('account.index')->with('success', config('messages.DB_DELETE'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Http\Requests\LoginRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends BackendController
{
    public function index()
    {
        if ($this->guard()->check()){
            return redirect()->route('order.index');
        }

        return view('backend.login.index');
    }

    public function auth(LoginRequest $request)
    {
        $info = $request->only(['login_id', 'password']);
        if ($this->guard()->attempt($info) ) {
            if($this->guard()->user()->status == config('const.status.enable')){
                return redirect()->route('order.index');
            }
            Auth::logout();
        }
        return redirect()->back()->withInput()->withErrors(['login_id' => config('messages.LOGIN_FAILED')]);
    }

    public function logout(Request $request)
    {
        $this->guard()->logout();
        $request->session()->flush();
        $request->session()->regenerate();
        return redirect()->route('login');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Repositories\CategoryRepository;

class CategoryController extends BackendController
{
    public $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    public function index()
    {
        $data = $this->categoryRepository->paging();
        return view('backend.category.index',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }
}

app/Http/Controllers/Backend/EventController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Repositories\EventCategoryRepository;
use App\Repositories\EventItemRepository;
use App\Repositories\EventRepository;
use App\Repositories\EventViewRepository;

class EventController extends BackendController
{
    public $eventRepository;
    public $eventViewRepository;
    public $eventItemRepository;
    public $eventCategoryRepository;

    public function __construct(
        EventRepository $eventRepository,
        EventCategoryRepository $eventCategoryRepository,
        EventItemRepository $evenItemRepository,
        EventViewRepository $eventViewRepository)
    {
        $this->eventRepository = $eventRepository;
        $this->eventViewRepository = $eventViewRepository;
        $this->eventItemRepository = $evenItemRepository;
        $this->eventCategoryRepository = $eventCategoryRepository;
    }

    public function index()
    {
        $data = $this->eventRepository->paging();
        return view('backend.event.index',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function item()
    {
        $data = $this->eventItemRepository->paging();
        return view('backend.event.item',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function category()
    {
        $data = $this->eventCategoryRepository->paging();
        return view('backend.event.category',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function view()
    {
        $data = $this->eventViewRepository->paging();
        return view('backend.event.view',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
    public function guard()
    {
        return Auth::guard(config('const.guard.backend'));
    }
}

resources/views/backend/banner/confirm_create.blade.php
@extends('backend.layouts.main')
@section('content')

    <div id="Contentwrap">
        <div id="PageContent" class="no_mar_bottom">
            <h2><i class="fas fa-image"></i> バナー登録</h2>
            <div class="order">
                <table class="sp_block flowtable">
                    <tr>
                        <th scope="row" style="width: 150px;">バナー画像</th>
                        <td>
                            <img src="{{asset(Session::get('banner_url_temp'))}}" width="260px">
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">リンク先URL</th>
                        <td>
                            {{Session::get('data')['link_url']}}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">公開期間</th>
                        <td>
                            {{Session::get('data')['public_start_date']}}〜{{Session::get('data')['public_end_date']}}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">ステータス</th>
                        <td>
                            {{config('const.status_banner')[Session::get('data')['status']]}}
                        </td>
                    </tr>
                </table>
            </div>
            <!--ContentFoot -->
        </div>
        <!--PageContent -->
        <form id="form_banner_confirm_create" action="{{ route('banner.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="contentfoot">
                <p class="btn Searchclear">
                    <button type="button" value="" onclick="System.redirectNoLoading('{{ route('banner.create',['flag' => config('const.flag')['from_confirm']])}}')"><i
                            class="fas fa-undo"></i> 戻る
                    </button>
                </p>
                <p class="btn register">
                    <button type="button" onclick="System.showDialog('banner','confirm_create')"
                            class="opener"><i class="fas fa-check"></i> 登録する
                    </button>
                </p>
            </div>
        </form>
        <!--PageContent -->

    </div>
    <!--Contentwrap -->
@endsection

resources/views/backend/banner/confirm_edit.blade.php
@extends('backend.layouts.main')
@section('content')

    <div id="Contentwrap">
        <div id="PageContent" class="no_mar_bottom">
            <h2><i class="fas fa-image"></i> バナー編集</h2>
            <div class="order">
                <table class="sp_block flowtable">
                    <tr>
                        <th scope="row" style="width: 150px;">バナー画像</th>
                        <td>
                            <img src="{{asset(Session::get('banner_url_temp_edit'))}}" width="260px">
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">リンク先URL</th>
                        <td>
                            {{Session::get('dataUpdate')['link_url']}}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">公開期間</th>
                        <td>
                            {{Session::get('dataUpdate')['public_start_date']}}〜{{Session::get('dataUpdate')['public_end_date']}}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" style="width: 150px;">ステータス</th>
                        <td>
                            {{config('const.status_banner')[Session::get('dataUpdate')['status']]}}
                        </td>
                    </tr>
                </table>
            </div>
            <!--ContentFoot -->
        </div>
        <!--PageContent -->
        <form id="form_banner_confirm_edit" action="{{ route('banner.update',Session::get('data')['id']) }}" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            <div class="contentfoot">
                <p class="btn Searchclear">
                    <button type="button" value=""
                            onclick="System.redirectNoLoading('{{ route('banner.edit',[Session::get('data')['id'] ,'flag' => config('const.flag')['from_confirm']]) }}')"><i
                            class="fas fa-undo"></i> 戻る
                    </button>
                </p>
                <p class="btn register">
                    <button type="button" value=""
                            onclick="System.showDialog('banner','confirm_edit')"
                            class="opener"><i class="fas fa-check"></i> 編集する
                    </button>
                </p>
            </div>
        </form>
        <!--PageContent -->

    </div>
    <!--Contentwrap -->
@endsection

resources/views/backend/banner/index.blade.php
@extends('backend.layouts.main')
@section('content')
    <div id="Contentwrap">
        @include('common.message_notification')
        <div id="PageContent">
            <h2><br/><i class="fas fa-image"></i> バナー一覧<span class="btn register btnMedium sp-mt-neg-77" style="margin-top:-40px;">
                    <button type="button" onclick="System.redirectNoLoading(' {{ route('banner.create') }} ')"
                            tabindex="14">
                        <i class="fas fa-plus"></i> バナー登録</button>
                </span>
            </h2>
            <div class="PageContentNav">
                @include('backend.elements.paging', ['results' => $listBanner])
                {{ $listBanner->appends(request()->input())->links() }}
            </div>
            <table class="OrderForm responsive tdcenter Bordertd table-hover">
                <tr>
                    <th scope="col" width="100px">@include("backend.elements.sortable", ["field" => "id", "title" => "ID"])</th>
                    <th scope="col">@include("backend.elements.sortable", ["field" => "banner_url", "title" => "バナー画像"])</th>
                    <th scope="col" style="width: 500px !important;">@include("backend.elements.sortable", ["field" => "public_start_date", "title" => "公開期間"])</th>
                    <th scope="col" width="130px">@include("backend.elements.sortable", ["field" => "status", "title" => "ステータス"])</th>
                    <th scope="col" style="max-width:130px">@include("backend.elements.sortable", ["field" => "link_url", "title" => "リンクURL"])</th>
                    <th scope="col" style="width: 110px;">編集</th>
                    <th scope="col" style="width: 110px;">削除</th>
                </tr>
                @if(!$listBanner->isEmpty())
                    @foreach($listBanner as $banner)
                        <tr>
                            <td>{{$banner->id}}</td>
                            <td style="text-align:left;"><img src="{{ asset($banner->banner_url)}}" width="200"></td>
                            <td style="text-align:left;">{{\Illuminate\Support\Carbon::parse($banner->public_start_date)->format('Y/m/d')}}
                                〜{{\Illuminate\Support\Carbon::parse($banner->public_end_date)->format('Y/m/d')}}</td>
                            <td style="text-align:left;" >{{config('const.status_banner')[$banner->status]}}</td>
                            <td style="text-align:left;" class="style-word link-content"><p class="width-240">{{$banner->link_url}}</p></td>
                            <td><p class="btnmini Edit">
                                    <a onclick="System.redirectNoLoading('{{ route('banner.edit',$banner->id) }}')"
                                       class="TextC">編集</a>
                                </p></td>
                            <td>
                                <form id="{{'form_banner_confirm_delete'.$banner->id}}" method="post"
                                      action="{{ route('banner.destroy', $banner->id) }}">
                                    {{ csrf_field() }}
                                    @method('DELETE')
                                    <p class="btnmini">
                                        <button href="#" type="button"
                                                onclick="System.showDialog('banner','confirm_delete', {{$banner->id}})"
                                                value="">削除
                                        </button>
                                    </p>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                    @include('backend.elements.no_data',['col' => 7])
                @endif

            </table>
            <div class="PageContentNav">
                {{ $listBanner->appends(request()->input())->links() }}
            </div>
        </div>
        <!--PageContent -->

    </div>
    <!--Contentwrap -->
@endsection