routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login', 'AuthController@auth')->name('auth_login');
Route::get('/logout', 'AuthController@logout')->name('logout');

Route::group(['middleware' => 'backend.auth:backend'], function() {
    Route::get('/', 'OrderController@index');

    Route::group(['prefix' => 'account'], function () {
        Route::post('/confirm', 'AccountController@confirm')->name('account.create.confirm');
        Route::post('/{id}/confirm', 'AccountController@confirm')->name('account.edit.confirm');
    });
    Route::resource('account', 'AccountController')->except(['show']);

    Route::group(['prefix' => 'banner'], function () {
        Route::post('/create/confirm', 'BannerController@createConfirm')->name('banner.create_confirm');
        Route::post('/edit/{id}/confirm', 'BannerController@editConfirm')->name('banner.edit_confirm');
    });
    Route::resource('banner', 'BannerController')->except(['show']);
    Route::resource('category', 'CategoryController')->only(['index']);

    Route::group(['prefix' => 'information'], function () {
        Route::post('/create/confirm', 'InformationController@confirm')->name('information.create.confirm');
        Route::post('/{id}/confirm', 'InformationController@confirm')->name('information.edit.confirm');
    });
    Route::resource('information', 'InformationController')->except(['show']);


    Route::resource('order', 'OrderController')->only(['index','show']);
    Route::get('order/{area_id}/{city_id}/shop', 'OrderController@getShop')->name('order.get.shop');

    Route::group(['prefix' => 'shop'], function () {
        Route::post('/confirm', 'ShopController@confirm')->name('shop.create.confirm');
        Route::post('/{id}/confirm', 'ShopController@confirm')->name('shop.edit.confirm');
        Route::get('/{area_id}/city', 'ShopController@getCity')->name('shop.get.city');
        Route::get('/getCity',"ShopController@getCityTest")->name('shop.getCity');

    });

    Route::resource('shop', 'ShopController')->except(['show']);
    Route::resource('user', 'UserController')->only(['index','show']);

    Route::group(['prefix' => 'event'], function () {
        Route::get('/index', 'EventController@index')->name('event.index');
        Route::get('/category', 'EventController@category')->name('event.category');
        Route::get('/item', 'EventController@item')->name('event.item');
        Route::get('/view', 'EventController@view')->name('event.view');
    });
    Route::group(['prefix' => 'item'], function () {
        Route::get('/index', 'ItemController@index')->name('item.index');
        Route::get('/detail', 'ItemController@detail')->name('item.detail');
        Route::get('/limited', 'ItemController@limited')->name('item.limited');
        Route::get('/list', 'ItemController@search')->name('item.list');
        Route::get('/name', 'ItemController@name')->name('item.name');
        Route::get('/point', 'ItemController@point')->name('item.point');
        Route::get('/price', 'ItemController@price')->name('item.price');
        Route::get('/shopCount', 'ItemController@shopCount')->name('item.shop_count');
        Route::get('/{category_code}/event', 'ItemController@getEventByCategory')->name('item.get.event');
        Route::get('/{item_code}/{shop_code}/{flag}', 'ItemController@updateStopFlag')->name('item.update.flag');

    });
});

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;


Route::middleware('web')->group(function () {
    Route::get('/', 'SiteController@index')->name('site.index');
    Route::get('/login', 'LoginController@index')->name('frontend.login');
    Route::get('/login-confirm', 'LoginController@loginConfirm')->name('frontend.login.confirm');
    Route::post('login', 'LoginController@authenticate')->name('authenticate_login');
    Route::get('/logout', 'LoginController@logout')->name('frontend.logout');
    Route::get('/password-reissue/{token}', 'SiteController@passwordReissue')->name('site.password_reissue');
    Route::post('/password-reissue', 'SiteController@passwordReissueAction')->name('site.password_reissue_action');
    Route::get('/password-reissue-comp', 'SiteController@passwordReissueComp')->name('site.password_reissue_comp');
    Route::get('/password-reminder', 'SiteController@passwordReminder')->name('site.password_reminder');
    Route::post('password-reminder', 'SiteController@sendMailPasswordReissue')->name('site.send_mail_password_reissue');
    //AJAX
    Route::group(['prefix' => 'ajax'], function () {
        Route::post('/render-by-map', 'AjaxController@renderShopByMap')->name('site.ajax.render_by_map');
        Route::post('/render-shop-by-city', 'AjaxController@renderShopByCity')->name('site.ajax.render_shop_by_city');
        Route::post('/get-event', 'AjaxController@getEvent')->name('site.ajax.get_event');
        Route::post('/get-product', 'AjaxController@getProduct')->name('site.ajax.get_product');
        Route::post('/render-city-popup', 'AjaxController@renderCityPopup')->name('site.render_city_popup');
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('/detail/{id}/{shopcode}/{keyitem}/{keyprouct}', 'ProductController@detail')->name('product.detail');
    });

    Route::get('/information-detail/{id}', 'InformationController@detail')->name('information.detail');

    Route::group(['prefix' => 'cart'], function () {
        Route::get('/', 'CartController@index')->name('cart.index');
        Route::get('/confirm', 'CartController@confirm')->name('cart.confirm');
        Route::get('/complete', 'CartController@complete')->name('cart.complete');
        Route::post('/add-to-cart', 'CartController@addToCart')->name('cart.add_to_cart');
        Route::post('/remove-item-cart', 'CartController@removeItemCart')->name('cart.remove_item_cart');
        Route::post('/on-load-box-cart', 'CartController@onLoadBoxCart')->name('cart.on_load_box_cart');
        Route::post('/check-item-cart', 'CartController@checkItemCart')->name('cart.check_item_cart');
        Route::post('/change-number-cart', 'CartController@changeNumberCart')->name('cart.change_number_cart');
        Route::post('/insert-cart', 'CartController@insertCart')->name('cart.insert_cart');
        Route::get('/not-registration', 'CartController@notRegistration')->name('cart.notregistration');
        Route::post('/not-registration-action', 'CartController@notRegistrationAction')->name('cart.notregistration.action');
        Route::post('/show-popup-remove', 'CartController@showPopupRemove')->name('cart.show_popup_remove');
    });

    Route::group(['prefix' => 'entry'], function () {
        Route::get('/', 'EntryController@index')->name('entry.index');
        Route::post('/','EntryController@postIndex')->name('entry.submit');
        Route::get('/register', 'EntryController@register')->name('entry.register');
    });

    Route::group(['prefix' => 'mypage','middleware'=>'frontend.auth'], function () {
        Route::get('', 'MypageController@index')->name('mypage.index');
        Route::get('/cancel-order-confirm/{slipNumber}', 'MypageController@cancelOrderConfirm')->name('mypage.cancel_order_confirm');
        Route::get('/cancel-order-complete/{slipNumber}', 'MypageController@cancelOrderComplete')->name('mypage.cancel_order_complete');
        Route::post('/cancel-order-complete-action', 'MypageController@updateCancelOrder')->name('mypage.cancel_order_complete_action');
        Route::get('/change_customer_info/{slip_number}', 'MypageController@changeCustomerInfo')->name('mypage.change_customer_info');
        Route::post('/change_customer_info/{slip_number}', 'MypageController@postChangeInfo')->name('mypage.post.change_customer_info');
        Route::post('/show-popup-cancel', 'MypageController@showPopupCancel')->name('mypage.show_popup_cancel');
    });
    Route::get('/change-password-entry', 'ChangeEmailPasswordController@changePasswordEntry')->name('mypage.change_password_entry');
    Route::post('/change-password-entry', 'ChangeEmailPasswordController@changePasswordEntryAction')->name('mypage.change_password_entry_action');
    Route::group(array('prefix' => 'static'), function () {
        Route::view('/guild', 'frontend/static/guild')->name('guild');
        Route::view('/privacy', 'frontend/static/privacy')->name('privacy');
        Route::view('/tokutei', 'frontend/static/tokutei')->name('tokutei');
        Route::view('/browser', 'frontend/static/browser')->name('browser');
        Route::view('/sitemap', 'frontend/static/sitemap')->name('sitemap');
        Route::view('/rule', 'frontend/static/rule')->name('rule');
        Route::get('/information', 'InformationController@index')->name('information');
        Route::get('/information/detail/{id}', 'InformationController@detail')->name('information.detail');
    });
});

routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/tsv', 'TsvController@index')->name('test.tsv');
Route::get('/tsv_all', 'TsvController@index_all')->name('test.tsv_all');
Route::get('/tsv_export', 'TsvExportController@export_tsv')->name('test.tsv_export');

app/Http/Controllers/Backend/AccountController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Http\Requests\AccountCreateRequest;
use App\Repositories\AccountRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends BackendController
{
    protected $accountRepository;

    public function __construct(AccountRepository $accountRepository)
    {
        $this->accountRepository = $accountRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $accounts = $this->accountRepository->searchCondition($request)->paginate(config('const.paging.backend'));
        return view('backend.account.index', compact('accounts'))
            ->with([
                'name' => $request->get('name'),
                'status' => $request->get('status'),
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        request()->session()->put('session_data', []);
        return view('backend.account.create');
    }

    /**
     * Show the form for confirm the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function confirm(AccountCreateRequest $request, $id = null)
    {
        $request->flash();
        $request->session()->put('session_data', $request->all());
        return view('backend.account.confirm')->with('account', $request->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(!$request->session()->has('session_data')){
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
        $data = $request->session()->get('session_data');
        $request->session()->forget('session_data');
        try {
            $this->accountRepository->create($data);
            return redirect()->route('account.index')->with('success', config('messages.DB_INSERT'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = $this->accountRepository->find($id);
        if ($account == null) {
            return redirect()->route('account.index')->with('error', config('messages.NO_DATA'));
        } else {
            $account = $account->toArray();
        }
        request()->session()->put('session_data', $account);
        return view('backend.account.create')->with('account', $account);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!$request->session()->has('session_data'))
        {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
        $data = $request->session()->get('session_data');
        $request->session()->forget('session_data');
        try {
            $this->accountRepository->update($id, $data);
            return redirect()->route('account.index')->with('success', config('messages.DB_UPDATE'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->accountRepository->softDelete($id);
            return redirect()->route('account.index')->with('success', config('messages.DB_DELETE'));
        } catch (\Exception $e) {
            return redirect()->route('account.index')->with('error', config('messages.SYSTEM_ERROR'));
        }
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Http\Requests\LoginRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends BackendController
{
    public function index()
    {
        if ($this->guard()->check()){
            return redirect()->route('order.index');
        }

        return view('backend.login.index');
    }

    public function auth(LoginRequest $request)
    {
        $info = $request->only(['login_id', 'password']);
        if ($this->guard()->attempt($info) ) {
            if($this->guard()->user()->status == config('const.status.enable')){
                return redirect()->route('order.index');
            }
            Auth::logout();
        }
        return redirect()->back()->withInput()->withErrors(['login_id' => config('messages.LOGIN_FAILED')]);
    }

    public function logout(Request $request)
    {
        $this->guard()->logout();
        $request->session()->flush();
        $request->session()->regenerate();
        return redirect()->route('login');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Repositories\CategoryRepository;

class CategoryController extends BackendController
{
    public $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    public function index()
    {
        $data = $this->categoryRepository->paging();
        return view('backend.category.index',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }
}

app/Http/Controllers/Backend/EventController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\BackendController;
use App\Repositories\EventCategoryRepository;
use App\Repositories\EventItemRepository;
use App\Repositories\EventRepository;
use App\Repositories\EventViewRepository;

class EventController extends BackendController
{
    public $eventRepository;
    public $eventViewRepository;
    public $eventItemRepository;
    public $eventCategoryRepository;

    public function __construct(
        EventRepository $eventRepository,
        EventCategoryRepository $eventCategoryRepository,
        EventItemRepository $evenItemRepository,
        EventViewRepository $eventViewRepository)
    {
        $this->eventRepository = $eventRepository;
        $this->eventViewRepository = $eventViewRepository;
        $this->eventItemRepository = $evenItemRepository;
        $this->eventCategoryRepository = $eventCategoryRepository;
    }

    public function index()
    {
        $data = $this->eventRepository->paging();
        return view('backend.event.index',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function item()
    {
        $data = $this->eventItemRepository->paging();
        return view('backend.event.item',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function category()
    {
        $data = $this->eventCategoryRepository->paging();
        return view('backend.event.category',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }

    public function view()
    {
        $data = $this->eventViewRepository->paging();
        return view('backend.event.view',
            [
                'listData' => $data,
                'params' => request()->all()
            ]
        );
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
    public function guard()
    {
        return Auth::guard(config('const.guard.backend'));
    }
}

resources/views/backend/account/confirm.blade.php
@extends('backend.layouts.main')
@section('content')
<div id="Contentwrap">
    <div id="PageContent" class="no_mar_bottom">
        <h2><i class="fas fa-users-cog"></i> アカウント{{ array_key_exists('id', Session::get('session_data')) ? '編集' : '登録'}}</h2>
        <div class="order">
            <table class="sp_block flowtable">
                <tr>
                    <th scope="row" style="width: 150px;">氏名</th>
                    <td>
                        {{$account['name']}}
                    </td>
                </tr>
                <tr>
                    <th scope="row">ログインID</th>
                    <td>
                        {{$account['login_id']}}
                    </td>
                </tr>
                <tr>
                    <th scope="row">パスワード</th>
                    <td>
                        *********
                    </td>
                </tr>
                <tr>
                    <th scope="row">ステータス</th>
                    <td>
                        {{$account['status'] ? '有効' : '無効'}}
                    </td>
                </tr>
            </table>
        </div>
        <!--ContentFoot -->
    </div>
    <!--PageContent -->
    <form method="post"
          action="{{ array_key_exists('id', Session::get('session_data')) ? route('account.update', $account['id']) : route('account.store')}}"
          id="form_account_{{array_key_exists('id', Session::get('session_data')) ? 'confirm_edit':'confirm_create'}}">
        {{ csrf_field() }}
        @if(array_key_exists('id', Session::get('session_data')))
            @method('PUT')
        @endif
        <div class="contentfoot">
            <p class="btn Searchclear">
                <button type="button"
                        onclick="window.location='{{ array_key_exists('id', Session::get('session_data')) ? route("account.edit", $account['id']):route("account.create") }}'"><i
                        class="fas fa-undo"></i> 戻る
                </button>
            </p>
            <p class="btn register">
                <button type="button" onclick="System.showDialog('account', '{{ array_key_exists('id', Session::get('session_data')) ? 'confirm_edit' : 'confirm_create'}}')"><i
                        class="fas fa-check"></i> {{ array_key_exists('id', Session::get('session_data')) ? '編集' : '登録'}}する
                </button>
            </p>
        </div>
        <!--PageContent -->
    </form>
</div>
<!--Contentwrap -->
@endsection

resources/views/backend/account/create.blade.php
@extends('backend.layouts.main')
@section('content')
    <div id="Contentwrap">
        <form method="post" action="{{ array_key_exists('id', Session::get('session_data')) ? route('account.edit.confirm', $account['id']) : route('account.create.confirm')}}" >
            {{ csrf_field() }}
            <div class="contenttop detail-btn-group">
                <p class="btn Searchclear">
                    <button type="button" onclick="System.redirectNoLoading('{{ route('account.index') }}')"><i
                            class="fas fa-list"></i> 一覧ページに戻る
                    </button>
                </p>
            </div>
            <div id="PageContent" class="no_mar_bottom">
                <h2><i class="fas fa-users-cog"></i> アカウント{{ array_key_exists('id', Session::get('session_data')) ? '編集' : '登録'}}</h2>
                @if(array_key_exists('id', Session::get('session_data')))
                    <input style="display: none" name="id" value="{{$account['id']}}">
                @endif
                <div class="order">
                    <table class="sp_block flowtable">
                        <tr>
                            <th scope="row" style="width: 150px;">氏名<span class="req"></span></th>
                            <td>
                                <div class="line required medium-input">
                                    <input type="text" tabindex="7"  name="name" placeholder="例）管理 太郎" value="{{ old('name', isset($account) ? $account['name'] : '')}}">
                                </div>
                                @include('backend.elements.validate_error', ['message' => $errors->first('name')])
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">ログインID<span class="req"></span></th>
                            <td>
                                <div class="line required medium-input">
                                    <input type="text" tabindex="8" name="login_id" placeholder="例）kanri" value="{{ old('login_id', isset($account) ? $account['login_id'] : '')}}">
                                </div>
                                @include('backend.elements.validate_error', ['message' => $errors->first('login_id')])
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">パスワード<span class="req"></span></th>
                            <td>
                                <div class="line required medium-input">
                                    <input type="password" tabindex="9" name="password" placeholder="8桁以上の半角英数字">
                                </div>
                                @include('backend.elements.validate_error', ['message' => $errors->first('password')])
                            </td>
                        </tr>
                        <tr>
                            <th width="158" style="width: 150px;" scope="row">ステータス<span class="req"></span></th>
                            <td>
                                <div class="rabutton labelfull">
                                    <input type="radio" name="status" id="cate11" value="1" tabindex="1" checked
                                        {{(isset($account['status']) && $account['status'] == 1) || (null !== old('status') && old('status') == 1)? "checked" : "" }}>
                                    <label for="cate11">有効</label>
                                    <input type="radio" name="status" id="cate12" value="0" tabindex="2"
                                        {{(isset($account['status']) && $account['status'] == 0) || (null !== old('status') && old('status') == 0)? "checked" : "" }}>
                                    <label for="cate12">無効</label>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                <!--ContentFoot -->
            </div>
            <!--PageContent -->

            <div class="contentfoot">
                <p class="btn clear">
                    <button type="button" onclick="System.redirectNoLoading('{{ route('account.index') }}')"><i
                            class="fas fa-list"></i> 一覧ページに戻る
                    </button>
                </p>
                <p class="btn register">
                    <button type="submit" onclick="System.showLoading()"><i
                            class="fas fa-check"></i> 確認する
                    </button>
                </p>
            </div>
            <!--PageContent -->
        </form>
    </div>
    <!--Contentwrap -->
@endsection

resources/views/backend/account/index.blade.php
@extends('backend.layouts.main')
@section('content')
    <div id="Contentwrap">
        @include('common.message_notification')
        <div id="PageContent">
            <form action="{{route('account.index')}}" method="get">
                <h2><i class="fas fa-search"></i> アカウント検索</h2>
                <div class="order">
                    <table class="sp_block">
                        <tr>
                            <th scope="row" style="width: 150px;">氏名</th>
                            <td colspan="4">
                                <div class="inline_block rel sp-w45 line">
                                    <input type="text" name="name" placeholder="氏名" tabindex="5" value="{{isset($name) ? $name : ''}}">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">ステータス</th>
                            <td colspan="3">
                                <div class="rabutton">
                                    <input type="radio" name="status" id="rank1" value="" checked="" tabindex="48"
                                        {{ isset($status) && $status == null ? "checked" : "" }}>
                                    <label for="rank1">全て</label>
                                    <input type="radio" name="status" id="rank2" value="1" tabindex="48"
                                        {{ isset($status) && $status == 1 ? "checked" : "" }}>
                                    <label for="rank2">有効</label>
                                    <input type="radio" name="status" id="rank3" value="0" tabindex="48"
                                        {{ isset($status) && $status == 0 ? "checked" : "" }}>
                                    <label for="rank3">無効</label>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="contentfoot">
                    <p class="btn Searchclear">
                        <button type="button" onclick="System.redirectLoading('{{ route('account.index') }}')" value="">
                            検索条件をクリア
                        </button>
                    </p>
                    <p class="btn Search">
                        <button type="submit" value="" onclick="System.showLoading()" tabindex="13"><img
                                src="{{ asset('backend/images/common/icon3.png') }}" alt="検索">検索
                        </button>
                    </p>
                </div>
                <!--ContentFoot -->
            </form>
        </div>
        <!--PageContent -->

        <div id="PageContent" class="pt60">
            <h2><i class="fas fa-users-cog"></i> アカウント一覧<span class="btn register btnMedium sp-mt-neg-85" style="margin-top:-40px;">
                    <button type="button" onclick="System.redirectNoLoading('{{ route('account.create') }}')"
                            tabindex="14"><i class="fas fa-user-plus"></i> アカウント登録</button>
                </span>
            </h2>

            <div class="PageContentNav">
                @include('backend/elements/paging', ['results' => $accounts])
                {{ $accounts->appends(request()->input())->links() }}
            </div>
            <table class="OrderForm responsive tdcenter Bordertd TextL table-hover">
                <tr>
                    <th scope="col">@include("backend/elements.sortable", ["field" => "id", "title" => "ID"])</th>
                    <th scope="col">@include("backend/elements.sortable", ["field" => "name", "title" => "氏名"])</th>
                    <th scope="col">@include("backend/elements.sortable", ["field" => "status", "title" => "ステータス"])</th>
                    <th scope="col">@include("backend/elements.sortable", ["field" => "login_id", "title" => "ログインID"])</th>
                    <th scope="col">編集</th>
                    <th scope="col">削除</th>
                </tr>
                @if(!$accounts->isEmpty())
                    @foreach($accounts as $account)
                        <tr>
                            <td>{{$account->id}}</td>
                            <td>{{$account->name}}</td>
                            <td>{{$account->status == 0 ? '無効' : '有効'}}</td>
                            <td>{{$account->login_id}}</td>
                            <td><p class="btnmini Edit"><a onclick="System.redirectNoLoading('{{ route('account.edit', $account->id) }}')"
                                                           class="TextC">編集</a></p></td>
                            <td>
                                @if ($account->id != \Illuminate\Support\Facades\Auth::id())
                                <form id="{{'form_account_confirm_delete'.$account->id}}" method="post"
                                      action="{{ route('account.destroy', $account->id) }}">
                                    {{ csrf_field() }}
                                    @method('DELETE')
                                    <p class="btnmini">
                                        <button type="button"
                                                onclick="Backend.showDialog('account', 'confirm_delete', {{$account->id}})">削除
                                        </button>
                                    </p>
                                </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @else
                    @include('backend/elements/no_data',['col' => 7])
                @endif
            </table>
            <div class="PageContentNav">
                {{ $accounts->appends(request()->input())->links() }}
            </div>
        </div>
        <!--PageContent -->
    </div>
    <!--Contentwrap -->
@endsection